// ConfigGenerator.swift — renders a Frigate config.yaml + container start script.
import Foundation

enum ConfigGenerator {

    /// Build the Frigate config.yaml text from the app settings.
    static func frigateYAML(_ c: AppConfig) -> String {
        var s = ""
        s += "# Generated by Frigate ANE Detector — do not edit by hand.\n"
        s += "auth:\n  reset_admin_password: \(c.resetAdminPassword)\n\n"

        s += "snapshots:\n  enabled: true\n  bounding_box: true\n  retain:\n    default: \(c.retentionEventDays)\n\n"

        // MQTT
        if c.mqtt.enabled && !c.mqtt.host.isEmpty {
            s += "mqtt:\n"
            s += "  enabled: true\n"
            s += "  host: \(c.mqtt.host)\n"
            s += "  port: \(c.mqtt.port)\n"
            s += "  user: \(c.mqtt.user)\n"
            s += "  password: \"\(c.mqtt.password)\"\n\n"
        } else {
            s += "mqtt:\n  enabled: false\n\n"
        }

        // Detector → our ANE ZMQ server on the Mac host
        let hostIP = macHostForContainer(c.detectorEndpoint)
        s += "detectors:\n  apple_silicon:\n    type: zmq\n    endpoint: tcp://\(hostIP):5555\n    request_timeout_ms: 2000\n\n"

        // Model
        s += "model:\n  model_type: \(c.yolo.modelType)\n"
        s += "  width: \(c.yolo.width)\n  height: \(c.yolo.height)\n"
        s += "  input_tensor: nchw\n  input_dtype: float\n"
        s += "  path: /config/model_cache/\(c.yolo.modelFile)\n\n"

        s += "ffmpeg:\n  hwaccel_args: []\n\n"

        // Local AI (GenAI scene descriptions via Ollama)
        if c.localAI.enabled {
            s += "genai:\n  provider: \(c.localAI.provider)\n"
            s += "  base_url: \(c.localAI.baseURL)\n  model: \(c.localAI.model)\n\n"
        }

        // Unique YAML key per camera (prevents Frigate's DuplicateKeyError).
        let names = uniqueNames(c.cameras)

        // go2rtc restreams (RTSP creds injected if provided)
        s += "go2rtc:\n  streams:\n"
        for (i, cam) in c.cameras.enumerated() {
            let nm = names[i]
            let main = withCreds(cam.streamURL, cam.rtspUser, cam.rtspPassword)
            let sub = withCreds(cam.subStreamURL, cam.rtspUser, cam.rtspPassword)
            if !cam.streamURL.isEmpty {
                s += "    \(nm):\n      - ffmpeg:\(main)#video=copy#audio=copy\n"
            }
            if !cam.subStreamURL.isEmpty {
                s += "    \(nm)_sub:\n      - ffmpeg:\(sub)#video=copy#audio=copy\n"
            }
        }
        s += "\n"

        // Cameras
        s += "cameras:\n"
        if c.cameras.isEmpty {
            s += "  # No cameras configured yet — add them in the setup wizard.\n"
        }
        for (i, cam) in c.cameras.enumerated() {
            if cam.streamURL.isEmpty { continue }   // skip incomplete cameras (no main stream)
            let nm = names[i]
            let sub = cam.subStreamURL.isEmpty ? nm : "\(nm)_sub"
            let order = cam.uiOrder > 0 ? cam.uiOrder : (i + 1)
            s += "  \(nm):\n"
            if !cam.friendlyName.isEmpty { s += "    friendly_name: \"\(cam.friendlyName)\"\n" }
            s += "    ui:\n      order: \(order)\n"
            s += "    enabled: true\n"
            s += "    ffmpeg:\n      inputs:\n"
            s += "        - path: rtsp://127.0.0.1:8554/\(nm)\n"
            s += "          input_args: preset-rtsp-restream\n"
            s += "          roles:\n            - record\n"
            s += "        - path: rtsp://127.0.0.1:8554/\(sub)\n"
            s += "          input_args: preset-rtsp-restream\n"
            s += "          roles:\n            - detect\n"
            s += "    detect:\n      enabled: \(cam.detect)\n      width: \(cam.detectWidth)\n      height: \(cam.detectHeight)\n      fps: \(cam.detectFPS)\n"
            let objs = cam.trackedObjects.isEmpty ? ["person"] : cam.trackedObjects
            s += "    objects:\n      track:\n"
            for o in objs { s += "        - \(o)\n" }
            s += "    record:\n      enabled: \(cam.record)\n"
            s += "      continuous:\n        days: \(c.retentionContinuousDays)\n"
            s += "      alerts:\n        retain:\n          days: \(c.retentionEventDays)\n"
            s += "      detections:\n        retain:\n          days: \(c.retentionEventDays)\n"
            let extra = cam.extraYAML.trimmingCharacters(in: .whitespacesAndNewlines)
            if !extra.isEmpty {
                for line in extra.split(separator: "\n", omittingEmptySubsequences: false) {
                    s += "    \(line)\n"   // indent under the camera block
                }
            }
        }
        s += "\nversion: 0.17-0\n"
        return s
    }

    /// Unique, safe YAML key per camera (Frigate rejects duplicate camera keys).
    /// Duplicates get _2, _3, … suffixes.
    private static func uniqueNames(_ cams: [CameraConfig]) -> [String] {
        var seen = Set<String>(), out: [String] = []
        for cam in cams {
            let base = safeName(cam.name)
            var name = base, n = 2
            while seen.contains(name) { name = "\(base)_\(n)"; n += 1 }
            seen.insert(name); out.append(name)
        }
        return out
    }

    /// Camera names become YAML keys + restream ids — must be safe (no spaces).
    private static func safeName(_ s: String) -> String {
        let lowered = s.lowercased()
        let mapped = lowered.map { ($0.isLetter || $0.isNumber) ? $0 : "_" }
        var out = String(mapped)
        while out.contains("__") { out = out.replacingOccurrences(of: "__", with: "_") }
        out = out.trimmingCharacters(in: CharacterSet(charactersIn: "_"))
        return out.isEmpty ? "camera" : out
    }

    /// Inject `user:pass@` into an rtsp URL if creds are given and not already present.
    private static func withCreds(_ url: String, _ user: String, _ pass: String) -> String {
        guard !user.isEmpty, let scheme = url.range(of: "://") else { return url }
        let after = url[scheme.upperBound...]
        if after.contains("@") { return url }           // URL already carries creds
        let head = url[..<scheme.upperBound]
        let enc: (String) -> String = { $0.addingPercentEncoding(withAllowedCharacters: .alphanumerics) ?? $0 }
        return "\(head)\(enc(user)):\(enc(pass))@\(after)"
    }

    /// The container reaches the Mac host over the Apple-container bridge.
    private static func macHostForContainer(_ endpoint: String) -> String {
        // default Apple container host gateway
        return "192.168.64.1"
    }

    /// Build the container launch script using the chosen storage path + config dir.
    static func startScript(_ c: AppConfig, configDir: String) -> String {
        var s = "#!/bin/bash\n"
        s += "set -e\nexport PATH=\"/usr/local/bin:/usr/bin:/bin:$PATH\"\n\n"
        s += "STORAGE=\"\(c.storagePath)\"\n"
        s += "CONFIG=\"\(configDir)\"\n"
        s += "IMAGE=\"\(c.frigateImage)\"\n\n"
        s += "# Safety: refuse to start if the storage path is missing/unmounted\n"
        s += "if [ ! -d \"$STORAGE\" ]; then\n"
        s += "  echo \"ERROR: storage path not available: $STORAGE\" >&2\n"
        s += "  exit 3\nfi\n\n"
        s += "container stop frigate 2>/dev/null || true\n"
        s += "container rm frigate 2>/dev/null || true\n\n"
        s += "container run -d --name frigate -m 4096M --cap-add SYS_ADMIN \\\n"
        s += "  --tmpfs /dev/shm:size=512m \\\n"
        s += "  -v \"$CONFIG\":/config \\\n"
        s += "  -v \"$STORAGE\":/media/frigate \\\n"
        s += "  -p 8971:8971 -p 8554:8554 -p 8555:8555 \\\n"
        s += "  \"$IMAGE\"\n\n"
        s += "echo \"Frigate started — UI at http://localhost:8971\"\n"
        return s
    }

    /// Write config.yaml + start script to the support dir. Returns the yaml path.
    @discardableResult
    static func writeAll(_ store: ConfigStore) throws -> URL {
        let c = store.config
        let yaml = frigateYAML(c)
        try yaml.write(to: store.frigateConfigYAML, atomically: true, encoding: .utf8)
        let script = startScript(c, configDir: store.frigateConfigDir.path)
        try script.write(to: store.startScriptURL, atomically: true, encoding: .utf8)
        try? FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: store.startScriptURL.path)
        // ensure recordings dir exists if it's the local default
        try? FileManager.default.createDirectory(atPath: c.storagePath, withIntermediateDirectories: true)
        return store.frigateConfigYAML
    }
}
